version: '3.9'

services:
  app:
    build: ./app
    command: yarn run dev --host
    volumes:
      - ./app:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - db

  server:
    environment:
      DATABASE_URL: "postgresql://postgres:root@db:5432"
      CLEAN_DB: ${CLEAN_DB:-false}
      SEED_DB: ${SEED_DB:-false}
      SHORT_DB: ${SHORT_DB:-false}
    entrypoint: ${ENTRYPOINT}
    command: ${CMD}
    build: ./server
    # entrypoint: [./docker-entrypoint.sh]
    # command: ["uvicorn", "main:app", "--host","127.0.0.1", "--port","5000", "--reload"]
    volumes:
      - ./server:/server
    ports:
      - "8000:8000"
    networks:
      - db
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      PGDATA: /data/postgres
    volumes:
      - /db:/data/postgres
      #- db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 1s
      timeout: 4s
      retries: 5


  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_PROXY_X_FOR_COUNT: '1'
      PGADMIN_CONFIG_PROXY_X_PROTO_COUNT: '1'
      PGADMIN_CONFIG_PROXY_X_HOST_COUNT: '1'
      PGADMIN_CONFIG_PROXY_X_PORT_COUNT: '1'
      PGADMIN_CONFIG_PROXY_X_PREFIX_COUNT: '1'
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
#  db:
  pgadmin:
