/*
  Warnings:

  - You are about to drop the `RECPIES` table. If the table is not empty, all the data it contains will be lost.

*/
-- DropForeignKey
ALTER TABLE "USER_likes_RECPIES" DROP CONSTRAINT "USER_likes_RECPIES_RECIPE_id_fkey";

-- DropTable
DROP TABLE "RECPIES";

-- CreateTable
CREATE TABLE "RECIPES" (
    "id" SERIAL NOT NULL,
    "name" TEXT NOT NULL,
    "slug" TEXT,
    "video_url" TEXT,
    "thumbnail_url" TEXT,
    "ratings_negative" INTEGER DEFAULT 0,
    "ratings_positive" INTEGER DEFAULT 0,
    "score" INTEGER DEFAULT 0,
    "cooking_style_big_batch" INTEGER DEFAULT 0,
    "cooking_style_kid_friendly" INTEGER DEFAULT 0,
    "cooking_style_bake" INTEGER DEFAULT 0,
    "meal_breakfast" INTEGER DEFAULT 0,
    "meal_bakery_goods" INTEGER DEFAULT 0,
    "cuisine_american" INTEGER DEFAULT 0,
    "meal_drinks" INTEGER DEFAULT 0,
    "difficulty_5_ingredients_or_less" INTEGER DEFAULT 0,
    "healthy_low_calorie" INTEGER DEFAULT 0,
    "difficulty_easy" INTEGER DEFAULT 0,
    "dietary_gluten_free" INTEGER DEFAULT 0,
    "dietary_vegetarian" INTEGER DEFAULT 0,
    "difficulty_under_1_hour" INTEGER DEFAULT 0,
    "difficulty_under_45_minutes" INTEGER DEFAULT 0,
    "healthy_high_protein" INTEGER DEFAULT 0,
    "dietary_kid_friendly" INTEGER DEFAULT 0,
    "cuisine_fusion" INTEGER DEFAULT 0,
    "method_steam" INTEGER DEFAULT 0,
    "cuisine_japanese" INTEGER DEFAULT 0,
    "dietary_comfort_food" INTEGER DEFAULT 0,
    "dietary_indulgent_sweets" INTEGER DEFAULT 0,
    "method_bake" INTEGER DEFAULT 0,
    "dietary_dairy_free" INTEGER DEFAULT 0,
    "cooking_style_one_pot_or_pan" INTEGER DEFAULT 0,
    "cooking_style_pan_fry" INTEGER DEFAULT 0,
    "dietary_healthy" INTEGER DEFAULT 0,
    "method_pan_fry" INTEGER DEFAULT 0,
    "healthy_low_fat" INTEGER DEFAULT 0,
    "healthy_low_sugar" INTEGER DEFAULT 0,
    "healthy_low_carb" INTEGER DEFAULT 0,
    "cooking_style_mashup" INTEGER DEFAULT 0,
    "meal_snacks" INTEGER DEFAULT 0,
    "seasonal_winter" INTEGER DEFAULT 0,
    "cuisine_british" INTEGER DEFAULT 0,
    "cooking_style_comfort_food" INTEGER DEFAULT 0,
    "healthy_high_fiber" INTEGER DEFAULT 0,
    "cuisine_french" INTEGER DEFAULT 0,
    "meal_desserts" INTEGER DEFAULT 0,
    "difficulty_under_15_minutes" INTEGER DEFAULT 0,
    "difficulty_under_30_minutes" INTEGER DEFAULT 0,
    "dietary_keto" INTEGER DEFAULT 0,
    "seasonal_summer" INTEGER DEFAULT 0,
    "cooking_style_no_bake_desserts" INTEGER DEFAULT 0,
    "dietary_vegan" INTEGER DEFAULT 0,
    "cuisine_mexican" INTEGER DEFAULT 0,
    "seasonal_spring" INTEGER DEFAULT 0,
    "cuisine_italian" INTEGER DEFAULT 0,
    "meal_lunch" INTEGER DEFAULT 0,
    "seasonal_fall" INTEGER DEFAULT 0,
    "cuisine_german" INTEGER DEFAULT 0,
    "cooking_style_meal_prep" INTEGER DEFAULT 0,
    "meal_dinner" INTEGER DEFAULT 0,
    "meal_appetizers" INTEGER DEFAULT 0,
    "meal_sides" INTEGER DEFAULT 0,
    "cuisine_african" INTEGER DEFAULT 0,
    "cuisine_middle_eastern" INTEGER DEFAULT 0,
    "method_deep_fry" INTEGER DEFAULT 0,
    "cuisine_latin_american" INTEGER DEFAULT 0,
    "method_grill" INTEGER DEFAULT 0,
    "cuisine_dominican" INTEGER DEFAULT 0,
    "dietary_pescatarian" INTEGER DEFAULT 0,
    "cuisine_seafood" INTEGER DEFAULT 0,
    "cuisine_chinese" INTEGER DEFAULT 0,
    "cuisine_greek" INTEGER DEFAULT 0,
    "dietary_contains_alcohol" INTEGER DEFAULT 0,
    "cuisine_indian" INTEGER DEFAULT 0,
    "cooking_style_steam" INTEGER DEFAULT 0,
    "cooking_style_stuffed" INTEGER DEFAULT 0,
    "cuisine_caribbean" INTEGER DEFAULT 0,
    "cuisine_filipino" INTEGER DEFAULT 0,
    "cuisine_taiwanese" INTEGER DEFAULT 0,
    "cuisine_korean" INTEGER DEFAULT 0,
    "cuisine_jamaican" INTEGER DEFAULT 0,
    "meal_brunch" INTEGER DEFAULT 0,
    "cuisine_swedish" INTEGER DEFAULT 0,
    "cooking_style_deep_fry" INTEGER DEFAULT 0,
    "cuisine_west_african" INTEGER DEFAULT 0,
    "cuisine_thai" INTEGER DEFAULT 0,
    "cuisine_vietnamese" INTEGER DEFAULT 0,
    "cuisine_peruvian" INTEGER DEFAULT 0,
    "cuisine_brazilian" INTEGER DEFAULT 0,
    "cooking_style_grill" INTEGER DEFAULT 0,
    "cuisine_bbq" INTEGER DEFAULT 0,
    "cuisine_kenyan" INTEGER DEFAULT 0,
    "cuisine_haitian" INTEGER DEFAULT 0,
    "cuisine_persian" INTEGER DEFAULT 0,
    "cuisine_ethiopian" INTEGER DEFAULT 0,
    "cuisine_cuban" INTEGER DEFAULT 0,
    "cuisine_puerto_rican" INTEGER DEFAULT 0,
    "cuisine_soul_food" INTEGER DEFAULT 0,
    "cuisine_indigenous" INTEGER DEFAULT 0,
    "cuisine_laotian" INTEGER DEFAULT 0,
    "cuisine_hawaiian" INTEGER DEFAULT 0,
    "method_no_bake_desserts" INTEGER DEFAULT 0,
    "cuisine_lebanese" INTEGER DEFAULT 0,
    "cuisine_south_african" INTEGER DEFAULT 0,
    "cuisine_venezuelan" INTEGER DEFAULT 0,

    CONSTRAINT "RECIPES_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "USER_likes_RECPIES" ADD CONSTRAINT "USER_likes_RECPIES_RECIPE_id_fkey" FOREIGN KEY ("RECIPE_id") REFERENCES "RECIPES"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
