-- CreateTable
CREATE TABLE "RECPIES" (
    "id" SERIAL NOT NULL,
    "name" TEXT NOT NULL,
    "slug" TEXT,
    "video_url" TEXT,
    "thumbnail_url" TEXT,
    "ratings_negative" TEXT,
    "ratings_positive" TEXT,
    "score" TEXT,
    "cooking_style_big_batch" TEXT,
    "cooking_style_kid_friendly" TEXT,
    "cooking_style_bake" TEXT,
    "meal_breakfast" TEXT,
    "meal_bakery_goods" TEXT,
    "cuisine_american" TEXT,
    "meal_drinks" TEXT,
    "difficulty_5_ingredients_or_less" TEXT,
    "healthy_low_calorie" TEXT,
    "difficulty_easy" TEXT,
    "dietary_gluten_free" TEXT,
    "dietary_vegetarian" TEXT,
    "difficulty_under_1_hour" TEXT,
    "difficulty_under_45_minutes" TEXT,
    "healthy_high_protein" TEXT,
    "dietary_kid_friendly" TEXT,
    "cuisine_fusion" TEXT,
    "method_steam" TEXT,
    "cuisine_japanese" TEXT,
    "dietary_comfort_food" TEXT,
    "dietary_indulgent_sweets" TEXT,
    "method_bake" TEXT,
    "dietary_dairy_free" TEXT,
    "cooking_style_one_pot_or_pan" TEXT,
    "cooking_style_pan_fry" TEXT,
    "dietary_healthy" TEXT,
    "method_pan_fry" TEXT,
    "healthy_low_fat" TEXT,
    "healthy_low_sugar" TEXT,
    "healthy_low_carb" TEXT,
    "cooking_style_mashup" TEXT,
    "meal_snacks" TEXT,
    "seasonal_winter" TEXT,
    "cuisine_british" TEXT,
    "cooking_style_comfort_food" TEXT,
    "healthy_high_fiber" TEXT,
    "cuisine_french" TEXT,
    "meal_desserts" TEXT,
    "difficulty_under_15_minutes" TEXT,
    "difficulty_under_30_minutes" TEXT,
    "dietary_keto" TEXT,
    "seasonal_summer" TEXT,
    "cooking_style_no_bake_desserts" TEXT,
    "dietary_vegan" TEXT,
    "cuisine_mexican" TEXT,
    "seasonal_spring" TEXT,
    "cuisine_italian" TEXT,
    "meal_lunch" TEXT,
    "seasonal_fall" TEXT,
    "cuisine_german" TEXT,
    "cooking_style_meal_prep" TEXT,
    "meal_dinner" TEXT,
    "meal_appetizers" TEXT,
    "meal_sides" TEXT,
    "cuisine_african" TEXT,
    "cuisine_middle_eastern" TEXT,
    "method_deep_fry" TEXT,
    "cuisine_latin_american" TEXT,
    "method_grill" TEXT,
    "cuisine_dominican" TEXT,
    "dietary_pescatarian" TEXT,
    "cuisine_seafood" TEXT,
    "cuisine_chinese" TEXT,
    "cuisine_greek" TEXT,
    "dietary_contains_alcohol" TEXT,
    "cuisine_indian" TEXT,
    "cooking_style_steam" TEXT,
    "cooking_style_stuffed" TEXT,
    "cuisine_caribbean" TEXT,
    "cuisine_filipino" TEXT,
    "cuisine_taiwanese" TEXT,
    "cuisine_korean" TEXT,
    "cuisine_jamaican" TEXT,
    "meal_brunch" TEXT,
    "cuisine_swedish" TEXT,
    "cooking_style_deep_fry" TEXT,
    "cuisine_west_african" TEXT,
    "cuisine_thai" TEXT,
    "cuisine_vietnamese" TEXT,
    "cuisine_peruvian" TEXT,
    "cuisine_brazilian" TEXT,
    "cooking_style_grill" TEXT,
    "cuisine_bbq" TEXT,
    "cuisine_kenyan" TEXT,
    "cuisine_haitian" TEXT,
    "cuisine_persian" TEXT,
    "cuisine_ethiopian" TEXT,
    "cuisine_cuban" TEXT,
    "cuisine_puerto_rican" TEXT,
    "cuisine_soul_food" TEXT,
    "cuisine_indigenous" TEXT,
    "cuisine_laotian" TEXT,
    "cuisine_hawaiian" TEXT,
    "method_no_bake_desserts" TEXT,
    "cuisine_lebanese" TEXT,
    "cuisine_south_african" TEXT,
    "cuisine_venezuelan" TEXT,

    CONSTRAINT "RECPIES_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "USERS" (
    "id" SERIAL NOT NULL,
    "name" TEXT,

    CONSTRAINT "USERS_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "USER_likes_RECPIES" (
    "USER_id" INTEGER NOT NULL,
    "RECIPE_id" INTEGER NOT NULL,

    CONSTRAINT "USER_likes_RECPIES_pkey" PRIMARY KEY ("USER_id","RECIPE_id")
);

-- AddForeignKey
ALTER TABLE "USER_likes_RECPIES" ADD CONSTRAINT "USER_likes_RECPIES_USER_id_fkey" FOREIGN KEY ("USER_id") REFERENCES "USERS"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "USER_likes_RECPIES" ADD CONSTRAINT "USER_likes_RECPIES_RECIPE_id_fkey" FOREIGN KEY ("RECIPE_id") REFERENCES "RECPIES"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
